update the workflow

diff --git a/.github/workflows/workflow-1.yml b/.github/workflows/workflow-1.yml
--- a/.github/workflows/workflow-1.yml
+++ b/.github/workflows/workflow-1.yml
@@ -38,6 +38,19 @@ jobs:
         id: fmt
         run: terraform -chdir=Dev/Network/Prod/ fmt -check
 
+      - name: Terraform Init
+        id: init
+        run: terraform -chdir=Dev/Network/Prod/ init
+      
+      - name: Terraform Validate
+        id: validate
+        run: terraform -chdir=Dev/Network/Prod/ validate -no-color
+
+      - name: Terraform Plan
+        id: plan
+        #if: github.event_name == 'pull_request'
+        run: terraform -chdir=Dev/Network/Prod/ plan -no-color -input=false
+        continue-on-error: true
 
       # - #name: Update Pull Request
       #   #uses: actions/github-script@v6
@@ -69,10 +82,10 @@ jobs:
       #         body: output
       #       })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: echo "terraform apply is not appplicable at the moment"
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: echo "terraform apply is not appplicable at the moment"
